"""Added constraints system

Revision ID: 273f60bb38f6
Revises: cfe8c813c839
Create Date: 2025-11-25 18:32:12.076670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273f60bb38f6'
down_revision: Union[str, Sequence[str], None] = 'cfe8c813c839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contradiction',
    sa.Column('medicament_name', sa.String(length=50), nullable=False),
    sa.Column('contradiction', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('medicament_name', 'contradiction')
    )
    op.create_table('patient_contradiction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('contradiction', sa.String(length=100), nullable=False),
    sa.CheckConstraint('char_length(contradiction) BETWEEN 1 AND 100', name='check_contradiction_name_length'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_medicament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medicament_name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescribed_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('char_length(medicament_name) BETWEEN 1 AND 100', name='check_medicament_name_length'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='check_valid_dates'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_medicament')
    op.drop_table('patient_contradiction')
    op.drop_table('contradiction')
    # ### end Alembic commands ###
