"""Initial generation

Revision ID: 55d1e600dfec
Revises: 
Create Date: 2025-12-05 14:21:25.697485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d1e600dfec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contradiction',
    sa.Column('medicament_name', sa.String(length=50), nullable=False),
    sa.Column('contradiction', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('medicament_name', 'contradiction')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('passport_number', sa.String(), nullable=False),
    sa.Column('insurance_number', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email ~ '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$'", name='check_email_format'),
    sa.CheckConstraint("first_name ~ '^[A-Z][a-z]+$'", name='check_first_name_format'),
    sa.CheckConstraint("gender IN ('female','male')", name='check_gender_format'),
    sa.CheckConstraint("last_name ~ '^[A-Z][a-z]+$'", name='check_last_name_format'),
    sa.CheckConstraint("patronymic ~ '^[A-Z][a-z]+$'", name='check_patronymic_format'),
    sa.CheckConstraint("phone_number ~ '^[0-9]+$'", name='check_phone_number_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('insurance_number'),
    sa.UniqueConstraint('passport_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email ~ '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$'", name='check_email_format'),
    sa.CheckConstraint("first_name ~ '^[A-Z][a-z]+$'", name='check_first_name_format'),
    sa.CheckConstraint("last_name ~ '^[A-Z][a-z]+$'", name='check_last_name_format'),
    sa.CheckConstraint("patronymic ~ '^[A-Z][a-z]+$'", name='check_patronymic_format'),
    sa.CheckConstraint("phone_number ~ '^[0-9]+$'", name='check_phone_number_format'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('patient_contradiction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('contradiction', sa.String(length=100), nullable=False),
    sa.CheckConstraint('char_length(contradiction) BETWEEN 1 AND 100', name='check_contradiction_name_length'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_medicament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medicament_name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescribed_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('char_length(medicament_name) BETWEEN 1 AND 100', name='check_medicament_name_length'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='check_valid_dates'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('office_number', sa.String(length=10), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.CheckConstraint('date >= CURRENT_DATE', name='check_future_date'),
    sa.CheckConstraint('end_time > start_time', name='check_valid_time_range'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('information', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'cancelled', 'no-show')", name='check_valid_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('schedule')
    op.drop_table('patient_medicament')
    op.drop_table('patient_contradiction')
    op.drop_table('doctor')
    op.drop_table('specialization')
    op.drop_table('patient')
    op.drop_table('contradiction')
    # ### end Alembic commands ###
