"""delete user type id

Revision ID: cc17b2cbf3ec
Revises: 046997f33204
Create Date: 2025-12-06 12:43:47.464834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc17b2cbf3ec'
down_revision: Union[str, Sequence[str], None] = '046997f33204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
